pipeline {
    agent any
    options {
        durabilityHint("PERFORMANCE_OPTIMIZED")
    }
    stages {
        stage("Test") {
            steps {
                echo "Hello World!"
            }
        }
    }
}