@Library('my-shared-library') _

pipeline {
    agent none
    stages {
        stage('Build') {
            log.info 'Starting'
            agent any
            steps {
                build('clean package')
            }
        }
        stage('Test') {
            agent any
            steps {
                echo("unstash 'app'")
                echo("sh 'make check'")
            }
            post {
                always {
                    log.info 'Finishing'
                }
            }
        }
    }
}
