@Library('my-shared-library') _

pipeline {
    agent none
    stages {
        stage('Build') {
            script {
                log.info 'Starting'
            }
            agent any
            steps {
                build('clean package')
            }
        }
        stage('Test') {
            agent any
            steps {
                echo("unstash 'app'")
                echo("sh 'make check'")
            }
            post {
                always {
                    script {
                        log.info 'Finishing'
                    }
                }
            }
        }
    }
}
